### ISSUE TITLE
JWT 수정

### ISSUE THREAD

**Issue by bbeomgeun** [WhaleDone22/WhaleDone-Server#73]
<h1> 이슈 내용 </h1>

- JWT 로직도 부족하고, 토큰 발행에 사용되는 메타정보도 다시 정리해야 할 필요가 있다.

<h1> To-do </h1>

- [x] secret key 수정
- [x] 유효 기간 수정
- [x] github action에 secret key 등록하기
- [x] 각 서버의 application.yml에 secret key 등록

<h1> 참고 사항 </h1>

-

**Comment by 55tree** [comment]
Yeah~

**Comment by bbeomgeun** [comment]
JWT 토큰 예외처리를 위해 AuthenticationEntryPoint 추가
1. JwtTokenProvider에서 예외 발생, exception 정보 set
2. 해당 예외는 AuthenticationEntryPoint에서 처리
3. sendRedirect를 통해 ExceptionController로 전달
- sendRedirect URL은 스프링 시큐리티 config에서 permit 해줘야 한다.
5. Controller에서 공통 예외 처리를 위해 CustomException 발생
6. ControllerAdvice에서 CustomException에 대한 처리
